### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by lkngtn** [1Hive/ideas#2]
A DAO focused blog may be a good non-technical project that people could contribute to that would help grow awareness for the project.  

Possible content:
- Project updates ( such as the redemptions app, or changes in organizations governance policies)
- Aragon Dao Interviews / Case Studies (Possible candidates: Mybit, OpenESQ, DappNode, Daonuts, Blank DAO, District0x, Althea)

**Comment by yeqbfgxjiq** [comment]
Are you imagining this as a Medium blog, or something written in markdown that could be integrated into a website?

**Comment by lkngtn** [comment]
I think markdown makes more sense because then it can be managed in github and post creation could be planned using issues and integrated into the projects flow. What do you think?

**Comment by yeqbfgxjiq** [comment]
Yeah this seems like a natural fit for Docusaurus. Once the react architecture is setup, any content changes happen in markdown. Adding a new blog post is as easy as creating a new markdown file in the `blog` folder. Since we already have another issue open talking about that, should we just go ahead and close this one?

**Comment by 0xGabi** [comment]
I would suggests a Medium blog to reach a broader audience. Maybe a combination of a small intro to the article on Medium with a link to the full article on the 1Hive Docusaurus Blog 🤔 (useful for 1Hive/mvp#5)

Really intrigue about the pros and cons of the two options, maybe we can get some metrics on views from a blog vs a Medium post form Aragon One team?

**Comment by yeqbfgxjiq** [comment]
Why not do both? The hard part is writing the content for the blog. It only takes 5min to post to Medium or Docusaurus. I think it makes sense to post on whatever channels people are on, but then mirror all content on the Docusaurus website so there's a central place for all things 1Hive. I can't describe how frustrating it's been doing research on blockchain projects that have content in 10 different places that are all out of date and out of sync. It makes it so much harder to learn/engage. It's like in React, you lift the state up to 1 shared source of truth and then disperse that to all the components that need to display it :)

Also, if people are on the website, they're much more likely to click on something else on the website and explore it. If people are on Medium, they're much more likely to click on another Medium post and go down a blogging rabbit hole.

Good call on learning from the rest of the Aragon team though. I'd really like to see more cross collaboration and info being shared across teams. Maybe they could even feature/share our 1st blog when we're ready to launch. Who would we need to talk to to make that happen?
- ftr started to reference aggregate ideas on social engagement/sharing [here](https://github.com/1Hive/ideas/issues/7), and since we already have a blog, but now we're talking about where to share content to engage/reach people maybe we should move this into that larger issue?

**Comment by yeqbfgxjiq** [comment]
Relevant to this discussion is an Issue I started in the [communication repo](https://github.com/1Hive/communication) to explore how we want to communicate and share stuff with the world. I think it makes sense to choose the channels we're going to focus on, then have all content posted to the website (and/or a #communication channel on Keybase) and people who maintain each channel can share activity/content from the website/community
- https://github.com/1Hive/communication/issues/1

**Comment by lkngtn** [comment]
Closing this as [we have a blog now](https://1hive.org/blog/)
